### ISSUE TITLE
mixin column margin

### ISSUE THREAD

**Issue by Gregcop1** [dummy-team/dummy#10]
replace with 

``` css
@mixin column { @include inline-block; margin: 0 0 0 $gutter; vertical-align: top;
    &:first-child{ margin: 0; }
}
```
