### ISSUE TITLE
Add default values to scss variables  

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy#46]
To ease the extraction process of components (or any file from dummy), initialise each variable used in file with a default value.
```scss
$variable: value !default;

.component { property: $variable; } 
```
