### ISSUE TITLE
Add magnifier behavior

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy#79]
Create a zoom effect on hover
``` scss
.magnifier {
  transition: all .2s;

  transform: translateZ(0);

  &:hover {
    box-shadow: 0 5px 15px rgba($black, .1);

    transform: scale(1.035);
  }
}
```

**Comment by Gregcop1** [comment]
Why shouldn't you restrain the scope of transition to `transform` instead of `all` ?

I've recently set all my transition duration to vars with default values in composant. Dunno if it's a good habit or not.

**Comment by Plou** [comment]
I stated all, to ease the color transition if there are any. I don't know if we can add transition to the target component like below else we'd have to rewrite all the transitions:

```html
  <div class="component magnifier"></div>
```

``` scss
.component { transition: background-color .3s;
  &:hover { background-color: LightGoldenRodYellow;
} 
```
