### ISSUE TITLE
go BEM ?

### ISSUE THREAD

**Issue by Plou** [dummy-team/dummy#88]
I think we should go towards the BEM naming system 

``` css
/* Plain CSS */
.article {
  font-size: 16px;
}

.article__title {
  font-size: 24px;
}

/* Using preprocessor */
.article {
  font-size: 16px;

  &__title {
    font-size: 24px;
  }
}
```

**Comment by Gregcop1** [comment]
Don't forget to mention a real example ;)
```
.news-item__header--active:hover { ... }
```

Without preprocessor, BEM is pain in the ass but with good preprocessor habits, I think it could be great

**Comment by Plou** [comment]
If the BEM is choosed,  we'll have to look into scss-lint `NestingDepth` : 

``` scss
.list {
  &-item {
    &-link {
      &:hover { text-decoration: none; }
    }
  }
}
```
nesting depth is calculated as 4 
```css
.list-item-link:hover {
  text-decoration: none;
}
```
